// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDyX84sr-S6aLtHc0XcvVRPCdN-MH62Y',
    appId: '1:689289956295:web:b584bb6d2d6457d02d67e2',
    messagingSenderId: '689289956295',
    projectId: 'end-pc-parts',
    authDomain: 'end-pc-parts.firebaseapp.com',
    storageBucket: 'end-pc-parts.firebasestorage.app',
    measurementId: 'G-JJ6GPK7304',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfq9-Iw3ECpj46DKp7e7-QiB-Bv7NyXEY',
    appId: '1:689289956295:android:eaeefae4c87735d02d67e2',
    messagingSenderId: '689289956295',
    projectId: 'end-pc-parts',
    storageBucket: 'end-pc-parts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGENqVjGWed1EhuOHuzTyjKx3SBD__5A',
    appId: '1:689289956295:ios:546f94c4502fe9a32d67e2',
    messagingSenderId: '689289956295',
    projectId: 'end-pc-parts',
    storageBucket: 'end-pc-parts.firebasestorage.app',
    iosBundleId: 'com.example.pcPartsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqGENqVjGWed1EhuOHuzTyjKx3SBD__5A',
    appId: '1:689289956295:ios:546f94c4502fe9a32d67e2',
    messagingSenderId: '689289956295',
    projectId: 'end-pc-parts',
    storageBucket: 'end-pc-parts.firebasestorage.app',
    iosBundleId: 'com.example.pcPartsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnDyX84sr-S6aLtHc0XcvVRPCdN-MH62Y',
    appId: '1:689289956295:web:008727ad7bdefab82d67e2',
    messagingSenderId: '689289956295',
    projectId: 'end-pc-parts',
    authDomain: 'end-pc-parts.firebaseapp.com',
    storageBucket: 'end-pc-parts.firebasestorage.app',
    measurementId: 'G-97WKVPRZHX',
  );
}
